### ISSUE TITLE
Possible bug in bal.tab with subclassification?

### ISSUE THREAD

**Issue by thomasklausch2** [ngreifer/cobalt#79]
I am trying to understand how bal.tab creates std. mean differences in sub-classes. I understand how it creates the simple std. mean difference, i.e. `(m1 - m0)/sqrt((V1+V0)/2)`. I checked this with the canonical example.

```
# Canonical example
data("lalonde", package = "cobalt")
lalonde$p.score <- glm(treat ~ age + educ + race, data = lalonde, 
                       family = "binomial")$fitted.values
lalonde$subclass <- findInterval(lalonde$p.score, 
                                 quantile(lalonde$p.score, 
                                          (0:6)/6), all.inside = TRUE)

# Calculate std. mean difference manually
m = aggregate(age ~ treat, FUN=mean, data = lalonde)
v = aggregate(age ~ treat, FUN=var, data = lalonde)
(m[2,2] - m[1,2] ) / sqrt( (v[2,2] + v[1,2])/2)

# Calculate same std. mean difference by bal.tab
bal.tab(treat ~  age,
        data = lalonde, stats = c('mean.diff'), 
        continuous = 'std', s.d.denom = 'pooled') # matches manual calculation
```

However, how does this work with subclasses? If I use the exactly same definition as above in each subclass my manual calculation does not match that of bal.tab. Is this a bug or my mistake or do I have a misconception on what bal.tab is supposed to do here? Thank you

```
# Now calculate std. mean differences within strata manually
m = aggregate(age ~ subclass + treat, FUN=mean, data = lalonde)
v = aggregate(age ~ subclass + treat, FUN=var, data = lalonde)

dif = m[7:12,3] - m[1:6,3]
vp  = (v[7:12,3]+v[1:6,3])/2
(std.dif = dif/sqrt(vp))

# Calculate same std. mean differences by bal.tab
bal.tab(treat ~  age,
        data = lalonde, stats = c('mean.diff'), 
        continuous = 'std', s.d.denom = 'pooled',
        subclass = "subclass", disp.subclass = TRUE) # does not match manual calculation
```

**Comment by ngreifer** [comment]
Hi Thomas,

Sorry about the confusion! Remember that all standardized mean differences are computed using the unadjusted variances in the denominator. So you should use the same denominator after subclassification as you do before subclassification. This helps isolate any changes in balance to changes in the means. The same strategy is used regardless of matching, weighting, or subclassification. When I replace the denominator in the adjusted SMDs with the original variances, I get the correct answers reported by `bal.tab()`.

**Comment by thomasklausch2** [comment]
Thank you for your swift reply, Noah!

Actually, I am surprised to read this, although I can follow its logic. I am surprised, because so far I have used the approach described in the Imbens and Rubin (2015) book, section 13.7.1. There, they advise to first pool the within-stratum mean differences by their weighted sum across strata, then pool the variances by taking the weighted sum of the pooled within-stratum variances, and then divide the pooled mean by the pooled variance. So this approach does it exactly the other way around (the authors also use a  different pooling approach for the variances as I did in the code, and I think there is also a typo in their variance formula).
 
Can you point me to any similarly authoritative reference documenting the approach you are taking?

**Comment by ngreifer** [comment]
I mean the following:

```r
m = aggregate(age ~ subclass + treat, FUN=mean, data = lalonde)
v = aggregate(age ~ treat, FUN=var, data = lalonde)

dif = m[7:12,3] - m[1:6,3]
vp  = (v[2,2] + v[1,2])/2
(std.dif = dif/sqrt(vp))
```
This is mentioned in the Getting Started vignette [here](https://ngreifer.github.io/cobalt/articles/cobalt.html#variance-in-standardized-mean-differences-and-correlations), where I cite two articles by Liz Stuart. But I maintain that I don't need an authoritative reference to use what is clearly (to me) the best practice. It's easy to think of counterexamples where using a separate denominator in each subclass causes problems that don't occur when using a single denominator (e.g., when there is little variation within one subclass, which is desirable, but large variation in another. See an example [here](https://stats.stackexchange.com/a/565705/116195).

I will also say that just because Imbens and Rubin recommend it, doesn't make it a good practice. For example, they recommend assessing balance using test statistics in some cases, when the literature nearly uniformly acknowledges this is a poor practice. In the end, balance assessment is an approximate endeavor anyway, and so it makes sense to use principled and defensible approaches before defaulting to what is recommended in the literature, especially when the literature itself may not be clear on the motivation for a given procedure. For example, there is no obvious motivation for computing the pooled variance as it is done in Rubin's works; it is stated as a given and has become a norm, but it is not always the best approach (i.e., because it weights the two groups equally, which is arbitrary anyway).

I think you can make whatever choice you want to make, but I have implemented only the choices that I think make sense and are defensible in `cobalt`.  I am of course willing to be wrong and make changes, but I would need a strong justification for making such a change, and to me there is much stronger justification for implementing the SMD as I have currently. I'm happy to answer any more questions you have about this; this is one of the topics I am asked most about.

**Comment by thomasklausch2** [comment]
Thanks for your explanations and references. I agree it makes sense to use this version of the pooled std. mean difference.
