### ISSUE TITLE
Saving love.plot() plots as images - wrong picture size

### ISSUE THREAD

**Issue by victorn1** [ngreifer/cobalt#9]
When I try to save love.plot() plots as WMF or EMF pictures specifying small picture size, e.g.., 3x5 inches, I get a wrong size of the WMF/EMF picture. The plot itself resides in the left upper corner of the picture.

I tried 

win.metafile("loveplot1.wmf" ,height=3,width=5)
love.plot(b)
dev.off()

And I tried to save the plot as EMF file from RStudio. The result was the same.

**Comment by ngreifer** [comment]
Can you please attach the output file in a comment? When I run your code I have the expected output, which is an image 3 inches high and 5 inches wide. Do you have similar problems with other `ggplot2` or `plot` objects? Do you have an option set so that your units are in inches rather than cm? Attached is what I get when I run your code.
[loveplot1.zip](https://github.com/ngreifer/cobalt/files/2123846/loveplot1.zip)

**Comment by victorn1** [comment]
Here is the code 

win.metafile("loveplot1.wmf" ,height=3,width=5)
love.plot(b4,var.names = varnames)
dev.off()

And the plot. 
[loveplot1.zip](https://github.com/ngreifer/cobalt/files/2126533/loveplot1.zip)

The code is called from RStudio running on a 4K display.

**Comment by victorn1** [comment]
Oh, thanks a lot! Running the same code from RGui produces a correct result.There may be something wrong with RStudio.
[loveplot1.zip](https://github.com/ngreifer/cobalt/files/2126593/loveplot1.zip)
